services:
  se7e-tools:
    container_name: se7e-tools
    build: .
    ports:
      - "3000:3000"
    networks:
      - portainer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.se7etools.rule=(Host(`se7e-tools.assessoriase7e.cloud`))"
      - "traefik.http.routers.se7etools.entrypoints=websecure"
      - "traefik.http.routers.se7etools.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.se7etools.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_DOWNLOAD=true
    volumes:
      - .:/app
      - /app/node_modules

networks:
  portainer:
    external: true
