services:
  se7e-tools:
    image: se7e-tools:latest
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 1GB
        reservations:
          memory: 512MB
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_DOWNLOAD=true
    volumes:
      - .:/app
      - /app/node_modules

networks:
  portainer:
    external: true
