version: "3.8"

services:
  app:
    container_name: se7e-tools
    build: .
    ports:
      - "3000:3000"
    networks:
      portainer:
        ipv4_address: 10.0.1.15
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_DOWNLOAD=true
    volumes:
      - .:/app
      - /app/node_modules

networks:
  portainer:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
