services:
  app:
    container_name: se7e-tools
    build: .
    ports:
      - "3000:3000"
    networks:
      portainer:
        ipv4_address: 10.0.1.15
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: "1.0"
          memory: 1GB
        reservations:
          memory: 512MB
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_DOWNLOAD=true
    volumes:
      - .:/app
      - /app/node_modules

networks:
  portainer:
    external: true
